---
title: "MHC deconv"
author: "Kaspar Bresser"
date: "29/07/2021"
output: 
  github_document:
    toc: true
  html_document: 
    theme: simplex
    highlight: pygments
    code_folding: show
    self_contained: TRUE
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      autodep  = TRUE,
                      cache = FALSE,
#                     comment = NA,
                      fig.width = 5,
                      fig.asp = 0.618,
                      fig.align = "center")

```


```{r loading}
library(tidyverse)
library(lemon)
library(ggpubr)
```

MHCdecon was run on all peptides detected from each melanoma line. https://services.healthtech.dtu.dk/services/MHCMotifDecon-1.0/


Load in the output tables

```{r}
dat <- list(read_tsv("Data/MHCdeconOutput/M026/output.xls"),
            read_tsv("Data/MHCdeconOutput/mel95/output.xls"),
            read_tsv("Data/MHCdeconOutput/NKITIL/output.xls")
)
```


Combine tables

```{r}
dat.table <- tibble(tumor = c("M026.X1", "SK-MEL-95", "NKIRTIL006"), data = dat)

dat.table
```


Assign rank scores. 

```{r}
dat.table %>% 
  unnest(col = data) %>% 
  mutate(assignment = case_when(RANK_SCORE > 20 ~ "unassigned",
                         TRUE ~ "assigned")) %>% 
  mutate(MHC = case_when(RANK_SCORE > 20 ~ "unassigned",
                         TRUE ~ MHC)) -> plot.dat 
#  count(tumor, MHC) -> plot.dat 

write_tsv(plot.dat, "Output/Fig_S1DEF.tsv")
```

Plot the fraction of peptides that were assigned or not-assigned

```{r}
ggplot(plot.dat, aes(x = tumor, fill = assignment))+
  geom_bar( position = "fill", width = .85)+
  scale_fill_manual(values = c( "green4", "grey"))+
  coord_flip()+
  theme_classic()+
  theme(panel.grid.major.x = element_line(), legend.position = "bottom")

ggsave("Figs/deconv_assigned_unassigned.pdf", width = 3.5, height = 4, scale = .8)
```


Plot the amount of peptides assigned to each allele

```{r}
ggplot(plot.dat, aes(x = MHC, fill = MHC))+
  geom_bar( position = "dodge")+
  facet_wrap(~tumor, scales = "free")+
  coord_flip()+
  theme_classic()+
  theme(panel.grid.major.x = element_line(), legend.position = "none")

ggsave("Figs/deconv_alleles.pdf", width = 7.5, height = 3, scale = .8)
```



```{r fig.width=10, fig.asp=.25}
plot.dat %>% 
  mutate(len = nchar(SEQUENCE)) %>% 
  group_by(MHC, tumor, len) %>% 
  summarise(n = n()) %>% 
  mutate(freq = (n / sum(n))*100) %>% 
  nest(data = -tumor) %>% 
  deframe() -> plot.lines


plot.list <- map2(plot.lines, names(plot.lines),

~ggplot(.x, aes(x = len, y = freq, color = MHC))+
    geom_line()+
    scale_x_continuous(breaks = 8:14)+
    theme_classic()+
    theme(panel.grid.major.y = element_line(), legend.position = "right")+
    ggtitle(.y)

)

ggarrange(plotlist = plot.list, nrow = 1)

ggsave("Figs/deconv_alleles_lengths.pdf", width = 12, height = 3, scale = .8)
```





```{r}
dat.table %>% 
  unnest(col = data) %>% 
  mutate(MHC = case_when(RANK_SCORE > 20 ~ "unassigned",
                         TRUE ~ MHC)) %>% 
  group_by(tumor, MHC) %>% 
  summarise(n = n()) %>% 
  mutate(freq = (n / sum(n))*100)
```


```{r}
dat.table %>% 
  unnest(col = data) %>% 
  mutate(MHC = case_when(RANK_SCORE > 20 ~ "unassigned",
                         TRUE ~ "assigned")) %>% 
  mutate(len = case_when(nchar(SEQUENCE) > 11 ~ "dropped",
                         nchar(SEQUENCE) < 9 ~ "dropped",
                         TRUE ~ "kept")) %>% 
  group_by(tumor, MHC, len) %>% 
  summarise(n = n()) %>% 
  mutate(freq = (n / sum(n))*100) %>% 
  filter(MHC == "unassigned")
```

